### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mimmi20** [actions/stale#89]
I got this message:

```shell
  Set up job3s
  LTS
Current runner version: '2.263.0'
Operating System
  Ubuntu
  18.04.4
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20200518.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200518.1/images/linux/Ubuntu1804-README.md
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/stale@v3'
  Run actions/stale@v33s
    debug-only: false
Run actions/stale@v3
  with:
    repo-token: ***
    days-before-stale: 60
    days-before-close: 7
    stale-issue-message: This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
  
    stale-pr-message: This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
  
    stale-issue-label: stale
    stale-pr-label: stale
    operations-per-run: 30
    remove-stale-when-updated: true
    debug-only: false
(node:2791) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/actions/stale/v3/dist/index.js:5050:10)
    at Command.toString (/home/runner/work/_actions/actions/stale/v3/dist/index.js:5044:35)
    at issueCommand (/home/runner/work/_actions/actions/stale/v3/dist/index.js:5007:30)
    at Object.issue (/home/runner/work/_actions/actions/stale/v3/dist/index.js:5011:5)
    at Object.error (/home/runner/work/_actions/actions/stale/v3/dist/index.js:7217:15)
    at /home/runner/work/_actions/actions/stale/v3/dist/index.js:3741:18
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/actions/stale/v3/dist/index.js:3718:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2791) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2791) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  Complete job
```

Is this an error?

**Comment by hross** [comment]
@mimmi20 there was an issue on github where the API was failing at one point. Can you send a link to your logs (if they are public) or confirm that recent runs of the stale action are working again? You shouldn't see that error anymore...

**Comment by mimmi20** [comment]
> Can you send a link to your logs

Do you mean this?
https://github.com/mimmi20/template/runs/720690492?check_suite_focus=true

If I rerun the actions, this one will fail again.

**Comment by hross** [comment]
thanks! I'll look into this.

**Comment by hross** [comment]
@mimmi20 my guess is this might be related to permissions (but I'm not sure yet). I added some updates (not merged into master yet) which should help troubleshoot and submitted a PR to your repo for using that branch to get better logging:

https://github.com/mimmi20/template/pull/12

**Comment by mimmi20** [comment]
@hross I merged your PR and will look tomorow into the action logs.

**Comment by hross** [comment]
I went ahead and tested and merged these changes into v3 tracking so feel free to update your yaml whenever back to the v3 tracking branch @mimmi20. whenever you get logs feel free to attach here and I'll see if I can troubleshoot the issue.

**Comment by hross** [comment]
@mimmi20 looks like an issue with the token you are using. I submitted a PR to your repo. Going to close this issue since I fixed the error handling and I think we know the issue now.
